baseURL = "https://acaif.ch/"
languageCode = "fr-CH"
title = "ACAIF"
timeZone = "Europe/Zurich"
buildFuture = true

[params]
  author = "ACAIF"
  site_logo = "/ACAIF-logo/ACAIF-logo.svg"
  description = "Site officiel de l'ACAIF, l'association des commerçants, artisans et industriels de Forel (Lavaux)."
  banners = [
    "/banners/2022-05-13-14-08.avif",
    "/banners/2022-05-13-14-09.avif",
    "/banners/2022-05-13-14-10.avif",
    "/banners/2022-10-04-15-01.avif",
    "/banners/2022-10-04-15-02-00.avif",
    "/banners/2022-10-04-15-02-12.avif",
    "/banners/2022-10-04-15-07.avif",
    "/banners/2022-12-12-15-58.avif",
  ]

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  members = "/members/:slug/"
  events = "/events/:contentbasename/"

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke/v2"

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Événements"
  url = "/events/"
  weight = 2

[[menu.main]]
  name = "Membres"
  url = "/members/"
  weight = 3
